### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Przemek2829/r-able#1]
Please remove https://github.com/Przemek2829/r-able/tree/master/__pycache__, it's auto-generated. Also, upload the new plugin to the plugin repository

**Comment by Przemek2829** [comment]
__pycache__ removed. Now I have problem while plugin upload:

![image](https://github.com/Przemek2829/r-able/assets/47052911/9c88a196-a30b-4072-b82c-3a2e316cbbe4)
